version: '2'

services:
  nginx:
    restart: always
    build: ./nginx
    volumes:
    - /opt/nginx/conf.d:/etc/nginx/conf.d/
    - /opt/nginx/html:/usr/share/nginx/html:Z
    - /var/log/nginx:/var/log/nginx
    ports:
    - "80:80"
    - "443:443"
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80
    #command: /bin/bash -c "envsubst < ./conf.d/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"